/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedNoAccessRouteImport } from './routes/_authenticated/no-access'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin/import'
import { Route as AuthenticatedParentIndexRouteImport } from './routes/_authenticated/parent/index'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher/index'
import { Route as AuthenticatedTeacherImportRouteImport } from './routes/_authenticated/teacher/import'
import { Route as AuthenticatedParentStudentStudentIdRouteImport } from './routes/_authenticated/parent/student/$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNoAccessRoute = AuthenticatedNoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParentIndexRoute =
  AuthenticatedParentIndexRouteImport.update({
    id: '/parent/',
    path: '/parent/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/teacher/',
    path: '/teacher/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherImportRoute =
  AuthenticatedTeacherImportRouteImport.update({
    id: '/teacher/import',
    path: '/teacher/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParentStudentStudentIdRoute =
  AuthenticatedParentStudentStudentIdRouteImport.update({
    id: '/parent/student/$studentId',
    path: '/parent/student/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/no-access': typeof AuthenticatedNoAccessRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/teacher/import': typeof AuthenticatedTeacherImportRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/parent/': typeof AuthenticatedParentIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/parent/student/$studentId': typeof AuthenticatedParentStudentStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/no-access': typeof AuthenticatedNoAccessRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/teacher/import': typeof AuthenticatedTeacherImportRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/parent': typeof AuthenticatedParentIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/parent/student/$studentId': typeof AuthenticatedParentStudentStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/no-access': typeof AuthenticatedNoAccessRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/teacher/import': typeof AuthenticatedTeacherImportRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/parent/': typeof AuthenticatedParentIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/parent/student/$studentId': typeof AuthenticatedParentStudentStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/no-access'
    | '/admin/import'
    | '/teacher/import'
    | '/admin/'
    | '/parent/'
    | '/teacher/'
    | '/parent/student/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/no-access'
    | '/admin/import'
    | '/teacher/import'
    | '/admin'
    | '/parent'
    | '/teacher'
    | '/parent/student/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/no-access'
    | '/_authenticated/admin/import'
    | '/_authenticated/teacher/import'
    | '/_authenticated/admin/'
    | '/_authenticated/parent/'
    | '/_authenticated/teacher/'
    | '/_authenticated/parent/student/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/no-access': {
      id: '/_authenticated/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof AuthenticatedNoAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parent/': {
      id: '/_authenticated/parent/'
      path: '/parent'
      fullPath: '/parent/'
      preLoaderRoute: typeof AuthenticatedParentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/import': {
      id: '/_authenticated/teacher/import'
      path: '/teacher/import'
      fullPath: '/teacher/import'
      preLoaderRoute: typeof AuthenticatedTeacherImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parent/student/$studentId': {
      id: '/_authenticated/parent/student/$studentId'
      path: '/parent/student/$studentId'
      fullPath: '/parent/student/$studentId'
      preLoaderRoute: typeof AuthenticatedParentStudentStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNoAccessRoute: typeof AuthenticatedNoAccessRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedTeacherImportRoute: typeof AuthenticatedTeacherImportRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedParentIndexRoute: typeof AuthenticatedParentIndexRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
  AuthenticatedParentStudentStudentIdRoute: typeof AuthenticatedParentStudentStudentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNoAccessRoute: AuthenticatedNoAccessRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedTeacherImportRoute: AuthenticatedTeacherImportRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedParentIndexRoute: AuthenticatedParentIndexRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
  AuthenticatedParentStudentStudentIdRoute:
    AuthenticatedParentStudentStudentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
